# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPlainTextEdit, QVBoxLayout, QHBoxLayout, QGridLayout, QComboBox, QLineEdit, QSpinBox, \
    QDoubleSpinBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # Удаляем жесткое задание размеров, чтобы макеты могли работать
        # Dialog.resize(1675, 1022)

        # Создаем главный вертикальный макет для всего окна
        self.verticalLayout_main = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_main.setObjectName("verticalLayout_main")

        # Название программы
        self.label_name_of_programm = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_of_programm.setFont(font)
        self.label_name_of_programm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_of_programm.setObjectName("label_name_of_programm")
        self.verticalLayout_main.addWidget(self.label_name_of_programm)

        # Горизонтальный макет для левой и правой частей
        self.horizontalLayout_content = QtWidgets.QHBoxLayout()
        self.horizontalLayout_content.setObjectName("horizontalLayout_content")

        # Левая часть
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")

        # Исходные данные
        self.label_name_timestep_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_timestep_2.setFont(font)
        self.label_name_timestep_2.setObjectName("label_name_timestep_2")
        self.verticalLayout_left.addWidget(self.label_name_timestep_2)

        # Параметры модели
        self.horizontalLayout_parameters = QtWidgets.QHBoxLayout()
        self.horizontalLayout_parameters.setObjectName("horizontalLayout_parameters")

        self.verticalLayout_labels = QtWidgets.QVBoxLayout()
        self.verticalLayout_labels.setObjectName("verticalLayout_labels")
        self.label_name_timestep = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_timestep.setFont(font)
        self.label_name_timestep.setObjectName("label_name_timestep")
        self.verticalLayout_labels.addWidget(self.label_name_timestep)

        self.label_name_epochs = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_epochs.setFont(font)
        self.label_name_epochs.setObjectName("label_name_epochs")
        self.verticalLayout_labels.addWidget(self.label_name_epochs)

        self.label_name_batch_size = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_batch_size.setFont(font)
        self.label_name_batch_size.setObjectName("label_name_batch_size")
        self.verticalLayout_labels.addWidget(self.label_name_batch_size)

        self.label_name_porog_anomaly = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_porog_anomaly.setFont(font)
        self.label_name_porog_anomaly.setObjectName("label_name_porog_anomaly")
        self.verticalLayout_labels.addWidget(self.label_name_porog_anomaly)
        self.horizontalLayout_parameters.addLayout(self.verticalLayout_labels)

        self.verticalLayout_inputs = QtWidgets.QVBoxLayout()
        self.verticalLayout_inputs.setObjectName("verticalLayout_inputs")
        self.spinBox_timestep_value = QtWidgets.QSpinBox(Dialog)
        self.spinBox_timestep_value.setObjectName("spinBox_timestep_value")
        self.verticalLayout_inputs.addWidget(self.spinBox_timestep_value)

        self.spinBox_epochs_value = QtWidgets.QSpinBox(Dialog)
        self.spinBox_epochs_value.setObjectName("spinBox_epochs_value")
        self.verticalLayout_inputs.addWidget(self.spinBox_epochs_value)

        self.spinBox_batch_size_value = QtWidgets.QSpinBox(Dialog)
        self.spinBox_batch_size_value.setObjectName("spinBox_batch_size_value")
        self.verticalLayout_inputs.addWidget(self.spinBox_batch_size_value)

        # Используем QDoubleSpinBox
        self.spinBox_porog_anomaly_value = QDoubleSpinBox(Dialog)
        self.spinBox_porog_anomaly_value.setObjectName("spinBox_porog_anomaly_value")
        self.verticalLayout_inputs.addWidget(self.spinBox_porog_anomaly_value)
        self.horizontalLayout_parameters.addLayout(self.verticalLayout_inputs)

        self.verticalLayout_load_and_vvod = QtWidgets.QVBoxLayout()
        self.verticalLayout_load_and_vvod.setObjectName("verticalLayout_load_and_vvod")
        self.label_name_load_model = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_load_model.setFont(font)
        self.label_name_load_model.setObjectName("label_name_load_model")
        self.verticalLayout_load_and_vvod.addWidget(self.label_name_load_model)

        self.pushButton_load_model = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_load_model.setFont(font)
        self.pushButton_load_model.setObjectName("pushButton_load_model")
        self.verticalLayout_load_and_vvod.addWidget(self.pushButton_load_model)

        self.label_name_vvod_data = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_vvod_data.setFont(font)
        self.label_name_vvod_data.setObjectName("label_name_vvod_data")
        self.verticalLayout_load_and_vvod.addWidget(self.label_name_vvod_data)

        self.pushButton_vvod_data = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_vvod_data.setFont(font)
        self.pushButton_vvod_data.setObjectName("pushButton_vvod_data")
        self.verticalLayout_load_and_vvod.addWidget(self.pushButton_vvod_data)
        self.horizontalLayout_parameters.addLayout(self.verticalLayout_load_and_vvod)
        self.verticalLayout_left.addLayout(self.horizontalLayout_parameters)

        # Обучение
        self.groupBox_learning = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_learning.setFont(font)
        self.groupBox_learning.setObjectName("groupBox_learning")
        self.verticalLayout_learning = QtWidgets.QVBoxLayout(self.groupBox_learning)
        self.verticalLayout_learning.setObjectName("verticalLayout_learning")
        self.label_name_load_static_date_for_learning = QtWidgets.QLabel(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_load_static_date_for_learning.setFont(font)
        self.label_name_load_static_date_for_learning.setObjectName("label_name_load_static_date_for_learning")
        self.verticalLayout_learning.addWidget(self.label_name_load_static_date_for_learning)
        self.pushButton_load_file_for_learning = QtWidgets.QPushButton(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_load_file_for_learning.setFont(font)
        self.pushButton_load_file_for_learning.setObjectName("pushButton_load_file_for_learning")
        self.verticalLayout_learning.addWidget(self.pushButton_load_file_for_learning)
        self.label_name_learn_model = QtWidgets.QLabel(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_learn_model.setFont(font)
        self.label_name_learn_model.setObjectName("label_name_learn_model")
        self.verticalLayout_learning.addWidget(self.label_name_learn_model)
        self.pushButton_learn_model = QtWidgets.QPushButton(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_learn_model.setFont(font)
        self.pushButton_learn_model.setObjectName("pushButton_learn_model")
        self.verticalLayout_learning.addWidget(self.pushButton_learn_model)
        self.label_name_save_model = QtWidgets.QLabel(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_save_model.setFont(font)
        self.label_name_save_model.setObjectName("label_name_save_model")
        self.verticalLayout_learning.addWidget(self.label_name_save_model)
        self.pushButton_save_model = QtWidgets.QPushButton(self.groupBox_learning)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_save_model.setFont(font)
        self.pushButton_save_model.setObjectName("pushButton_save_model")
        self.verticalLayout_learning.addWidget(self.pushButton_save_model)
        self.verticalLayout_left.addWidget(self.groupBox_learning)

        # Тестирование
        self.groupBox_testing = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_testing.setFont(font)
        self.groupBox_testing.setObjectName("groupBox_testing")
        self.verticalLayout_testing = QtWidgets.QVBoxLayout(self.groupBox_testing)
        self.verticalLayout_testing.setObjectName("verticalLayout_testing")
        self.label_name_load_test_file = QtWidgets.QLabel(self.groupBox_testing)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_load_test_file.setFont(font)
        self.label_name_load_test_file.setObjectName("label_name_load_test_file")
        self.verticalLayout_testing.addWidget(self.label_name_load_test_file)
        self.pushButton_load_test_file = QtWidgets.QPushButton(self.groupBox_testing)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_load_test_file.setFont(font)
        self.pushButton_load_test_file.setObjectName("pushButton_load_test_file")
        self.verticalLayout_testing.addWidget(self.pushButton_load_test_file)
        self.label_name_test_model = QtWidgets.QLabel(self.groupBox_testing)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_test_model.setFont(font)
        self.label_name_test_model.setObjectName("label_name_test_model")
        self.verticalLayout_testing.addWidget(self.label_name_test_model)
        self.pushButton_test_model = QtWidgets.QPushButton(self.groupBox_testing)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_test_model.setFont(font)
        self.pushButton_test_model.setObjectName("pushButton_test_model")
        self.verticalLayout_testing.addWidget(self.pushButton_test_model)
        self.verticalLayout_left.addWidget(self.groupBox_testing)

        # Онлайн-тестирование
        self.groupBox_online = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_online.setFont(font)
        self.groupBox_online.setObjectName("groupBox_online")
        self.verticalLayout_online = QtWidgets.QVBoxLayout(self.groupBox_online)
        self.verticalLayout_online.setObjectName("verticalLayout_online")
        self.label_online_port = QtWidgets.QLabel(self.groupBox_online)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_online_port.setFont(font)
        self.label_online_port.setObjectName("label_online_port")
        self.verticalLayout_online.addWidget(self.label_online_port)
        self.spinBox_online_port = QtWidgets.QSpinBox(self.groupBox_online)
        self.spinBox_online_port.setRange(1024, 65535)
        self.spinBox_online_port.setValue(12345)
        self.spinBox_online_port.setObjectName("spinBox_online_port")
        self.verticalLayout_online.addWidget(self.spinBox_online_port)
        self.pushButton_start_online_testing = QtWidgets.QPushButton(self.groupBox_online)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_start_online_testing.setFont(font)
        self.pushButton_start_online_testing.setObjectName("pushButton_start_online_testing")
        self.verticalLayout_online.addWidget(self.pushButton_start_online_testing)
        self.pushButton_stop_online_testing = QtWidgets.QPushButton(self.groupBox_online)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.pushButton_stop_online_testing.setFont(font)
        self.pushButton_stop_online_testing.setObjectName("pushButton_stop_online_testing")
        self.verticalLayout_online.addWidget(self.pushButton_stop_online_testing)
        self.verticalLayout_left.addWidget(self.groupBox_online)

        # Текстовая зона
        self.verticalLayout_text_zone = QtWidgets.QVBoxLayout()
        self.verticalLayout_text_zone.setObjectName("verticalLayout_text_zone")
        self.label_name_information_about_work_network = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_information_about_work_network.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_information_about_work_network.setObjectName("label_name_information_about_work_network")
        self.verticalLayout_text_zone.addWidget(self.label_name_information_about_work_network)
        self.text_zone = QtWidgets.QPlainTextEdit(Dialog)
        # Устанавливаем политику размера для растяжения
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.text_zone.setSizePolicy(sizePolicy)
        self.text_zone.setObjectName("text_zone")
        self.verticalLayout_text_zone.addWidget(self.text_zone)
        self.verticalLayout_left.addLayout(self.verticalLayout_text_zone)

        self.horizontalLayout_content.addLayout(self.verticalLayout_left)

        # Правая часть (графики)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")

        # График ошибки реконструкции
        self.label_name_widget_plot_reconstruction_error = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_widget_plot_reconstruction_error.setFont(font)
        self.label_name_widget_plot_reconstruction_error.setObjectName("label_name_widget_plot_reconstruction_error")
        self.verticalLayout_right.addWidget(self.label_name_widget_plot_reconstruction_error)
        self.widget_plot_reconstruction_error = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.widget_plot_reconstruction_error.setSizePolicy(sizePolicy)
        self.widget_plot_reconstruction_error.setObjectName("widget_plot_reconstruction_error")
        self.verticalLayout_right.addWidget(self.widget_plot_reconstruction_error)

        # График ошибки обучения
        self.label_widget_name_plot_loss = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_widget_name_plot_loss.setFont(font)
        self.label_widget_name_plot_loss.setObjectName("label_widget_name_plot_loss")
        self.verticalLayout_right.addWidget(self.label_widget_name_plot_loss)
        self.widget_plot_loss = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.widget_plot_loss.setSizePolicy(sizePolicy)
        self.widget_plot_loss.setObjectName("widget_plot_loss")
        self.verticalLayout_right.addWidget(self.widget_plot_loss)

        # График сравнения
        self.label_name_widget_plot_anomaly_comparison = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(13)
        self.label_name_widget_plot_anomaly_comparison.setFont(font)
        self.label_name_widget_plot_anomaly_comparison.setObjectName("label_name_widget_plot_anomaly_comparison")
        self.verticalLayout_right.addWidget(self.label_name_widget_plot_anomaly_comparison)
        self.widget_plot_anomaly_comparison = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.widget_plot_anomaly_comparison.setSizePolicy(sizePolicy)
        self.widget_plot_anomaly_comparison.setObjectName("widget_plot_anomaly_comparison")
        self.verticalLayout_right.addWidget(self.widget_plot_anomaly_comparison)

        self.horizontalLayout_content.addLayout(self.verticalLayout_right)
        self.verticalLayout_main.addLayout(self.horizontalLayout_content)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Автоэнкодер CNN-LSTM"))
        self.label_name_of_programm.setText(_translate("Dialog", "AnomalyGuard"))
        self.label_name_timestep_2.setText(_translate("Dialog", "Исходные данные"))
        self.label_name_timestep.setText(_translate("Dialog", "Размер окна"))
        self.label_name_epochs.setText(_translate("Dialog", "Количество эпох обучения"))
        self.label_name_batch_size.setText(_translate("Dialog", "Размер батча"))
        self.label_name_porog_anomaly.setText(_translate("Dialog", "Порог аномалии"))
        self.label_name_load_model.setText(_translate("Dialog", "Для загрузки уже обученной модели"))
        self.pushButton_load_model.setText(_translate("Dialog", "Загрузить модель"))
        self.label_name_vvod_data.setText(_translate("Dialog", "Ввести необходимые данные для работы"))
        self.pushButton_vvod_data.setText(_translate("Dialog", "Ввод данных"))
        self.groupBox_learning.setTitle(_translate("Dialog", "Обучение"))
        self.label_name_load_static_date_for_learning.setText(
            _translate("Dialog", "Загрузка файла со статистическими данными для обучения"))
        self.pushButton_load_file_for_learning.setText(_translate("Dialog", "Загрузить файл"))
        self.pushButton_load_file_for_learning.setMinimumHeight(30)
        self.label_name_learn_model.setText(_translate("Dialog", "Для обучения модели на новом файле"))
        self.pushButton_learn_model.setText(_translate("Dialog", "Обучить модель"))
        self.pushButton_learn_model.setMinimumHeight(30)
        self.label_name_save_model.setText(_translate("Dialog", "Для сохранения обученной модели"))
        self.pushButton_save_model.setText(_translate("Dialog", "Сохранить модель"))
        self.pushButton_save_model.setMinimumHeight(30)
        self.groupBox_testing.setTitle(_translate("Dialog", "Тестирование"))
        self.label_name_load_test_file.setText(
            _translate("Dialog", "Загрузка файла, со статистическими данными для тестирования"))
        self.pushButton_load_test_file.setText(_translate("Dialog", "Загрузить файл"))
        self.label_name_test_model.setText(_translate("Dialog", "Для тестирования модели на реальном объекте"))
        self.pushButton_test_model.setText(_translate("Dialog", "Тестировать модель"))
        self.groupBox_online.setTitle(_translate("Dialog", "Онлайн-тестирование"))
        self.label_online_port.setText(_translate("Dialog", "Порт для прослушивания"))
        self.pushButton_start_online_testing.setText(_translate("Dialog", "Старт"))
        self.pushButton_stop_online_testing.setText(_translate("Dialog", "Стоп"))
        self.label_name_information_about_work_network.setText(
            _translate("Dialog", "Информация о работе нейронной сети"))
        self.label_name_widget_plot_reconstruction_error.setText(
            _translate("Dialog", "График ошибки реконструкции (MSE)"))
        self.label_widget_name_plot_loss.setText(_translate("Dialog", "График ошибки обучения и валидации"))
        self.label_name_widget_plot_anomaly_comparison.setText(
            _translate("Dialog", "Сравнение: предсказания vs истинные аномалии"))